package com.rmrdigitalmedia.esm.models ;

import java.util.Map ;
import java.util.HashMap ;
import java.sql.Connection ;
import java.sql.SQLException ;
import com.javaranch.common.Str ;
import com.javaranch.db.DBResults ;
import com.javaranch.db.TableFacade ;

/** Strongly typed access to the database table "SPACE_CHECKLIST_AUDIT".
 *
 * This source file was automatically generated by "Jenny the db code generator"
 * based on information found in the database.  Do not modify this file!
 *
 * For more information on Jenny, see http://www.javaranch.com/jenny.jsp
 *
 *
 * Most of the methods are static so you don't need to instantiate a copy of this class 
 * to do your work.  The primary access methods are:
 * <ul>
 *
 *     <b>getRow()/getRows()/getAllRows()</b><br>
 *     <b>search() </b><i>like getRows(), but you can specify which columns you want back</i><br>
 *     <b>update()</b><br>
 *     <b>delete()</b><br>
 *     <b>insert()</b><br>
 *
 * </ul>
 *
 * These methods all have the option of passing in a connection as the first parameter.
 * Usually you won't use a connection directly, but sometimes it's useful.
 *
 * The getRows() methods all return an array of Row objects or a single Row object.  The
 * row object is easy to work with and provides strong type checking.  If your table has
 * a lot of columns, and your search will return a lot of rows, you might want to consider
 * using a search() method instead.  You lose some of your strong type checking, but 
 * you might go a lot easier on memory.  In these cases, you will want to make sure you
 * use the column name constants found at the top of this class.
 *
 */
public class SpaceChecklistAuditTable
{

    private static Implementation imp = new Implementation();

    public static final String tableName = "SPACE_CHECKLIST_AUDIT";

    public static final String idColumnName = "ID";
    public static final String spaceIDColumnName = "SPACE_ID";
    public static final String q1DimsHColumnName = "Q1_DIMS_H";
    public static final String q1DimsWColumnName = "Q1_DIMS_W";
    public static final String q1DimsLColumnName = "Q1_DIMS_L";
    public static final String q1CommentsColumnName = "Q1_COMMENTS";
    public static final String q2CheckboxColumnName = "Q2_CHECKBOX";
    public static final String q2DescColumnName = "Q2_DESC";
    public static final String q3CheckboxColumnName = "Q3_CHECKBOX";
    public static final String q3CommentsColumnName = "Q3_COMMENTS";
    public static final String q4CheckboxColumnName = "Q4_CHECKBOX";
    public static final String q4DimsHColumnName = "Q4_DIMS_H";
    public static final String q4DimsWColumnName = "Q4_DIMS_W";
    public static final String q4CommentsColumnName = "Q4_COMMENTS";
    public static final String q5CheckboxColumnName = "Q5_CHECKBOX";
    public static final String q5CommentsColumnName = "Q5_COMMENTS";
    public static final String q6CheckboxColumnName = "Q6_CHECKBOX";
    public static final String q6CommentsColumnName = "Q6_COMMENTS";
    public static final String q7CheckboxColumnName = "Q7_CHECKBOX";
    public static final String q7RatingColumnName = "Q7_RATING";
    public static final String q7CommentsColumnName = "Q7_COMMENTS";
    public static final String q8CheckboxColumnName = "Q8_CHECKBOX";
    public static final String q8RatingColumnName = "Q8_RATING";
    public static final String q8CommentsColumnName = "Q8_COMMENTS";
    public static final String q9CheckboxColumnName = "Q9_CHECKBOX";
    public static final String q9RatingColumnName = "Q9_RATING";
    public static final String q9CommentsColumnName = "Q9_COMMENTS";
    public static final String q10CheckboxColumnName = "Q10_CHECKBOX";
    public static final String q10RatingColumnName = "Q10_RATING";
    public static final String q10CommentsColumnName = "Q10_COMMENTS";
    public static final String q11CheckboxColumnName = "Q11_CHECKBOX";
    public static final String q11CommentsColumnName = "Q11_COMMENTS";
    public static final String q12CheckboxColumnName = "Q12_CHECKBOX";
    public static final String q12CommentsColumnName = "Q12_COMMENTS";
    public static final String q13CheckboxColumnName = "Q13_CHECKBOX";
    public static final String q13CommentsColumnName = "Q13_COMMENTS";
    public static final String q14CheckboxColumnName = "Q14_CHECKBOX";
    public static final String q14CommentsColumnName = "Q14_COMMENTS";
    public static final String q15CheckboxColumnName = "Q15_CHECKBOX";
    public static final String q15CommentsColumnName = "Q15_COMMENTS";
    public static final String q16CheckboxColumnName = "Q16_CHECKBOX";
    public static final String q16CommentsColumnName = "Q16_COMMENTS";
    public static final String q17CheckboxColumnName = "Q17_CHECKBOX";
    public static final String q17CommentsColumnName = "Q17_COMMENTS";

    private static String[] allColumns =
    {
        idColumnName , spaceIDColumnName , q1DimsHColumnName , q1DimsWColumnName , q1DimsLColumnName , q1CommentsColumnName , q2CheckboxColumnName , q2DescColumnName , q3CheckboxColumnName , q3CommentsColumnName , q4CheckboxColumnName , q4DimsHColumnName , q4DimsWColumnName , q4CommentsColumnName , q5CheckboxColumnName , q5CommentsColumnName , q6CheckboxColumnName , q6CommentsColumnName , q7CheckboxColumnName , q7RatingColumnName , q7CommentsColumnName , q8CheckboxColumnName , q8RatingColumnName , q8CommentsColumnName , q9CheckboxColumnName , q9RatingColumnName , q9CommentsColumnName , q10CheckboxColumnName , q10RatingColumnName , q10CommentsColumnName , q11CheckboxColumnName , q11CommentsColumnName , q12CheckboxColumnName , q12CommentsColumnName , q13CheckboxColumnName , q13CommentsColumnName , q14CheckboxColumnName , q14CommentsColumnName , q15CheckboxColumnName , q15CommentsColumnName , q16CheckboxColumnName , q16CommentsColumnName , q17CheckboxColumnName , q17CommentsColumnName , 
    };

    /** You probably want to use the static methods for most of your access, but once in a while you might need to
     *  pass an instance object to a method that knows how to work with these sorts of tables.
     */
    public static Implementation getInstance()
    {
        return imp ;
    }

    /** For use by unit testing, although you could provide your own implementation here if
     *  you wanted to.
     *  
     *  To use this in your unit testing, create an instance of MockSpaceChecklistAuditTable and pass
     *  it in here.  Then set your mock return values, call the method you are testing and examine
     *  the mock values that are now set!
     */
    public static void setInstance( SpaceChecklistAuditTable.Implementation instance  )
    {
        imp = instance ;
    }

    /** Exposed for unit testing purposes only! */
    static class Implementation extends TableFacade
    {

        /** Exposed for unit testing purposes only! */
        Implementation()
        {
            super( EsmFacade.getInstance() , tableName );
        }

        // convert a DBResults object to an array of Row objects.
        // requires that all of the columns be represented in the DBResults object and in the right order
        private static Row[] rowArray( DBResults r )
        {
            Row[] rows = new Row[ r.size() ];
            for( int i = 0 ; i < rows.length ; i++ )
            {
                rows[ i ] = new Row( r.getRow( i ) );
            }
            return rows ;
        }

        /** Instantiate an empty Row object */
        public Row getRow()
        {
            // if you are wondering about why this method is so lame - it's for unit testing!
            // The idea is that during unit testing, a different test object will be returned here.
            // To learn more about unit testing with Jenny generated code, visit <a href="http://www.javaranch.com/jenny.jsp">www.javaranch.com/jenny.jsp</a>
            return new Row();
        }

        /** Instantiate a Row object and fill its content based on a search for the ID. 
         *
         * Return null if not found.  Return first item if more than one found.
         */
        public Row getRow( Connection con , int id ) throws SQLException
        {
            Row row = new Row( this.search( con , "ID" , String.valueOf( id ) , allColumns ) );
            return row.dataLoadedFromDatabase() ? row : null ;
        }

        /** Instantiate a Row object and fill its content based on a search for the ID.
         *
         * Return null if not found.
         */
        public Row getRow( long id ) throws SQLException
        {
            Row row = new Row( this.search( "ID" , String.valueOf( id ) , allColumns ) );
            return row.dataLoadedFromDatabase() ? row : null ;
        }

        /** Instantiate a Row object and fill its content based on a search
         *
         * Return null if not found.
         */
        public Row getRow( Connection con , String column , String searchText ) throws SQLException
        {
            Row row = new Row( this.search( con , column , searchText , allColumns ) );
            return row.dataLoadedFromDatabase() ? row : null ;
        }

        /** Instantiate a Row object and fill its content based on a search
         *
         * Return null if not found.
         */
        public Row getRow( String column , String searchText ) throws SQLException
        {
            Row row = new Row( this.search( column , searchText , allColumns ) );
            return row.dataLoadedFromDatabase() ? row : null ;
        }

        /** Return an array of length zero if nothing found */
        public Row[] getRows( Connection con , String column , String searchText ) throws SQLException
        {
            return rowArray( this.search( con , column , searchText , allColumns ) );
        }

        /** Return an array of length zero if nothing found */
        public Row[] getRows( String column , String searchText ) throws SQLException
        {
            return rowArray( this.search( column , searchText , allColumns ) );
        }

        /** Return an array of length zero if nothing found */
        public Row[] getRows( Connection con , String column , String[] searchText ) throws SQLException
        {
            return rowArray( this.search( con , column , searchText , allColumns ) );
        }

        /** Return an array of length zero if nothing found */
        public Row[] getRows( String column , String[] searchText ) throws SQLException
        {
            return rowArray( this.search( column , searchText , allColumns ) );
        }

        /** Return an array of length zero if nothing found */
        public Row[] getRows( Connection con , String whereClause ) throws SQLException
        {
            return rowArray( this.search( con , whereClause , allColumns ) );
        }

        /** Return an array of length zero if nothing found */
        public Row[] getRows( String whereClause ) throws SQLException
        {
            return rowArray( this.search( whereClause , allColumns ) );
        }

        /** Return an array of length zero if nothing found */
        public Row[] getAllRows( Connection con ) throws SQLException
        {
            return rowArray( this.search( con , allColumns ) );
        }

        /** Return an array of length zero if nothing found */
        public Row[] getAllRows() throws SQLException
        {
            return rowArray( this.search( allColumns ) );
        }

        public void update( Connection con , int id , Map data ) throws SQLException
        {
            this.update( con , "ID" , String.valueOf( id ) , data );
        }

        public void update( int id , Map data ) throws SQLException
        {
            this.update( "ID" , String.valueOf( id ) , data );
        }

        public void delete( Connection con , long id ) throws SQLException
        {
            this.delete( con , "ID" , String.valueOf( id ) );
        }

        public void delete( long id ) throws SQLException
        {
            this.delete( "ID" , String.valueOf( id ) );
        }

        public long insertAndGetID( Connection con , Map data ) throws SQLException
        {
            return this.insertAndGetID( con , data , "ID" );
        }

        public long insertAndGetID( Map data ) throws SQLException
        {
            return this.insertAndGetID( data , "ID" );
        }


    }

    public static class Row
    {

        private boolean dataLoadedFromDatabase = false ;

        private int id ;
        private int spaceID ;
        private String q1DimsH ;
        private String q1DimsW ;
        private String q1DimsL ;
        private String q1Comments ;
        private String q2Checkbox ;
        private String q2Desc ;
        private String q3Checkbox ;
        private String q3Comments ;
        private String q4Checkbox ;
        private String q4DimsH ;
        private String q4DimsW ;
        private String q4Comments ;
        private String q5Checkbox ;
        private String q5Comments ;
        private String q6Checkbox ;
        private String q6Comments ;
        private String q7Checkbox ;
        private int q7Rating ;
        private boolean q7RatingNull = true ;
        private String q7Comments ;
        private String q8Checkbox ;
        private int q8Rating ;
        private boolean q8RatingNull = true ;
        private String q8Comments ;
        private String q9Checkbox ;
        private int q9Rating ;
        private boolean q9RatingNull = true ;
        private String q9Comments ;
        private String q10Checkbox ;
        private int q10Rating ;
        private boolean q10RatingNull = true ;
        private String q10Comments ;
        private String q11Checkbox ;
        private String q11Comments ;
        private String q12Checkbox ;
        private String q12Comments ;
        private String q13Checkbox ;
        private String q13Comments ;
        private String q14Checkbox ;
        private String q14Comments ;
        private String q15Checkbox ;
        private String q15Comments ;
        private String q16Checkbox ;
        private String q16Comments ;
        private String q17Checkbox ;
        private String q17Comments ;

        /** for internal use only!   If you need a row object, use getRow(). */
        Row()
        {
        }

        private Row( String[] data )
        {
            if ( data != null )
            {
                this.id =  Str.toInt( data[0] );
                this.spaceID =  Str.toInt( data[1] );
                this.q1DimsH = data[2];
                this.q1DimsW = data[3];
                this.q1DimsL = data[4];
                this.q1Comments = data[5];
                this.q2Checkbox = data[6];
                this.q2Desc = data[7];
                this.q3Checkbox = data[8];
                this.q3Comments = data[9];
                this.q4Checkbox = data[10];
                this.q4DimsH = data[11];
                this.q4DimsW = data[12];
                this.q4Comments = data[13];
                this.q5Checkbox = data[14];
                this.q5Comments = data[15];
                this.q6Checkbox = data[16];
                this.q6Comments = data[17];
                this.q7Checkbox = data[18];
                this.q7RatingNull = ( data[19] == null );
                this.q7Rating = q7RatingNull ? 0 : Str.toInt( data[19] );
                this.q7Comments = data[20];
                this.q8Checkbox = data[21];
                this.q8RatingNull = ( data[22] == null );
                this.q8Rating = q8RatingNull ? 0 : Str.toInt( data[22] );
                this.q8Comments = data[23];
                this.q9Checkbox = data[24];
                this.q9RatingNull = ( data[25] == null );
                this.q9Rating = q9RatingNull ? 0 : Str.toInt( data[25] );
                this.q9Comments = data[26];
                this.q10Checkbox = data[27];
                this.q10RatingNull = ( data[28] == null );
                this.q10Rating = q10RatingNull ? 0 : Str.toInt( data[28] );
                this.q10Comments = data[29];
                this.q11Checkbox = data[30];
                this.q11Comments = data[31];
                this.q12Checkbox = data[32];
                this.q12Comments = data[33];
                this.q13Checkbox = data[34];
                this.q13Comments = data[35];
                this.q14Checkbox = data[36];
                this.q14Comments = data[37];
                this.q15Checkbox = data[38];
                this.q15Comments = data[39];
                this.q16Checkbox = data[40];
                this.q16Comments = data[41];
                this.q17Checkbox = data[42];
                this.q17Comments = data[43];
                dataLoadedFromDatabase = true ;
            }
        }

        private Row( DBResults results )
        {
            this( results.getRow(0) );
        }

        public int getID()
        {
            return id ;
        }

        public void setID( int id )
        {
            this.id = id ;
        }


        public int getSpaceID()
        {
            return spaceID ;
        }

        public void setSpaceID( int spaceID )
        {
            this.spaceID = spaceID ;
        }


        public String getQ1DimsH()
        {
            return q1DimsH ;
        }

        public void setQ1DimsH( String q1DimsH )
        {
            this.q1DimsH = q1DimsH ;
        }


        public String getQ1DimsW()
        {
            return q1DimsW ;
        }

        public void setQ1DimsW( String q1DimsW )
        {
            this.q1DimsW = q1DimsW ;
        }


        public String getQ1DimsL()
        {
            return q1DimsL ;
        }

        public void setQ1DimsL( String q1DimsL )
        {
            this.q1DimsL = q1DimsL ;
        }


        public String getQ1Comments()
        {
            return q1Comments ;
        }

        public void setQ1Comments( String q1Comments )
        {
            this.q1Comments = q1Comments ;
        }


        public String getQ2Checkbox()
        {
            return q2Checkbox ;
        }

        public void setQ2Checkbox( String q2Checkbox )
        {
            this.q2Checkbox = q2Checkbox ;
        }


        public String getQ2Desc()
        {
            return q2Desc ;
        }

        public void setQ2Desc( String q2Desc )
        {
            this.q2Desc = q2Desc ;
        }


        public String getQ3Checkbox()
        {
            return q3Checkbox ;
        }

        public void setQ3Checkbox( String q3Checkbox )
        {
            this.q3Checkbox = q3Checkbox ;
        }


        public String getQ3Comments()
        {
            return q3Comments ;
        }

        public void setQ3Comments( String q3Comments )
        {
            this.q3Comments = q3Comments ;
        }


        public String getQ4Checkbox()
        {
            return q4Checkbox ;
        }

        public void setQ4Checkbox( String q4Checkbox )
        {
            this.q4Checkbox = q4Checkbox ;
        }


        public String getQ4DimsH()
        {
            return q4DimsH ;
        }

        public void setQ4DimsH( String q4DimsH )
        {
            this.q4DimsH = q4DimsH ;
        }


        public String getQ4DimsW()
        {
            return q4DimsW ;
        }

        public void setQ4DimsW( String q4DimsW )
        {
            this.q4DimsW = q4DimsW ;
        }


        public String getQ4Comments()
        {
            return q4Comments ;
        }

        public void setQ4Comments( String q4Comments )
        {
            this.q4Comments = q4Comments ;
        }


        public String getQ5Checkbox()
        {
            return q5Checkbox ;
        }

        public void setQ5Checkbox( String q5Checkbox )
        {
            this.q5Checkbox = q5Checkbox ;
        }


        public String getQ5Comments()
        {
            return q5Comments ;
        }

        public void setQ5Comments( String q5Comments )
        {
            this.q5Comments = q5Comments ;
        }


        public String getQ6Checkbox()
        {
            return q6Checkbox ;
        }

        public void setQ6Checkbox( String q6Checkbox )
        {
            this.q6Checkbox = q6Checkbox ;
        }


        public String getQ6Comments()
        {
            return q6Comments ;
        }

        public void setQ6Comments( String q6Comments )
        {
            this.q6Comments = q6Comments ;
        }


        public String getQ7Checkbox()
        {
            return q7Checkbox ;
        }

        public void setQ7Checkbox( String q7Checkbox )
        {
            this.q7Checkbox = q7Checkbox ;
        }


        public int getQ7Rating()
        {
            return q7Rating ;
        }

        public void setQ7Rating( int q7Rating )
        {
            this.q7Rating = q7Rating ;
            q7RatingNull = false ;
        }

        public void setQ7Rating( Integer q7Rating )
        {
            q7RatingNull = ( q7Rating == null );
            if ( q7RatingNull )
            {
                this.q7Rating = 0 ;
            }
            else
            {
                this.q7Rating = q7Rating.intValue() ;
            }
        }

        public boolean isQ7RatingNull()
        {
            return q7RatingNull ;
        }

        public void setQ7RatingNull( boolean q7RatingNull )
        {
            this.q7RatingNull = q7RatingNull ;
            if ( q7RatingNull )
            {
                q7Rating = 0 ;
            }
        }


        public String getQ7Comments()
        {
            return q7Comments ;
        }

        public void setQ7Comments( String q7Comments )
        {
            this.q7Comments = q7Comments ;
        }


        public String getQ8Checkbox()
        {
            return q8Checkbox ;
        }

        public void setQ8Checkbox( String q8Checkbox )
        {
            this.q8Checkbox = q8Checkbox ;
        }


        public int getQ8Rating()
        {
            return q8Rating ;
        }

        public void setQ8Rating( int q8Rating )
        {
            this.q8Rating = q8Rating ;
            q8RatingNull = false ;
        }

        public void setQ8Rating( Integer q8Rating )
        {
            q8RatingNull = ( q8Rating == null );
            if ( q8RatingNull )
            {
                this.q8Rating = 0 ;
            }
            else
            {
                this.q8Rating = q8Rating.intValue() ;
            }
        }

        public boolean isQ8RatingNull()
        {
            return q8RatingNull ;
        }

        public void setQ8RatingNull( boolean q8RatingNull )
        {
            this.q8RatingNull = q8RatingNull ;
            if ( q8RatingNull )
            {
                q8Rating = 0 ;
            }
        }


        public String getQ8Comments()
        {
            return q8Comments ;
        }

        public void setQ8Comments( String q8Comments )
        {
            this.q8Comments = q8Comments ;
        }


        public String getQ9Checkbox()
        {
            return q9Checkbox ;
        }

        public void setQ9Checkbox( String q9Checkbox )
        {
            this.q9Checkbox = q9Checkbox ;
        }


        public int getQ9Rating()
        {
            return q9Rating ;
        }

        public void setQ9Rating( int q9Rating )
        {
            this.q9Rating = q9Rating ;
            q9RatingNull = false ;
        }

        public void setQ9Rating( Integer q9Rating )
        {
            q9RatingNull = ( q9Rating == null );
            if ( q9RatingNull )
            {
                this.q9Rating = 0 ;
            }
            else
            {
                this.q9Rating = q9Rating.intValue() ;
            }
        }

        public boolean isQ9RatingNull()
        {
            return q9RatingNull ;
        }

        public void setQ9RatingNull( boolean q9RatingNull )
        {
            this.q9RatingNull = q9RatingNull ;
            if ( q9RatingNull )
            {
                q9Rating = 0 ;
            }
        }


        public String getQ9Comments()
        {
            return q9Comments ;
        }

        public void setQ9Comments( String q9Comments )
        {
            this.q9Comments = q9Comments ;
        }


        public String getQ10Checkbox()
        {
            return q10Checkbox ;
        }

        public void setQ10Checkbox( String q10Checkbox )
        {
            this.q10Checkbox = q10Checkbox ;
        }


        public int getQ10Rating()
        {
            return q10Rating ;
        }

        public void setQ10Rating( int q10Rating )
        {
            this.q10Rating = q10Rating ;
            q10RatingNull = false ;
        }

        public void setQ10Rating( Integer q10Rating )
        {
            q10RatingNull = ( q10Rating == null );
            if ( q10RatingNull )
            {
                this.q10Rating = 0 ;
            }
            else
            {
                this.q10Rating = q10Rating.intValue() ;
            }
        }

        public boolean isQ10RatingNull()
        {
            return q10RatingNull ;
        }

        public void setQ10RatingNull( boolean q10RatingNull )
        {
            this.q10RatingNull = q10RatingNull ;
            if ( q10RatingNull )
            {
                q10Rating = 0 ;
            }
        }


        public String getQ10Comments()
        {
            return q10Comments ;
        }

        public void setQ10Comments( String q10Comments )
        {
            this.q10Comments = q10Comments ;
        }


        public String getQ11Checkbox()
        {
            return q11Checkbox ;
        }

        public void setQ11Checkbox( String q11Checkbox )
        {
            this.q11Checkbox = q11Checkbox ;
        }


        public String getQ11Comments()
        {
            return q11Comments ;
        }

        public void setQ11Comments( String q11Comments )
        {
            this.q11Comments = q11Comments ;
        }


        public String getQ12Checkbox()
        {
            return q12Checkbox ;
        }

        public void setQ12Checkbox( String q12Checkbox )
        {
            this.q12Checkbox = q12Checkbox ;
        }


        public String getQ12Comments()
        {
            return q12Comments ;
        }

        public void setQ12Comments( String q12Comments )
        {
            this.q12Comments = q12Comments ;
        }


        public String getQ13Checkbox()
        {
            return q13Checkbox ;
        }

        public void setQ13Checkbox( String q13Checkbox )
        {
            this.q13Checkbox = q13Checkbox ;
        }


        public String getQ13Comments()
        {
            return q13Comments ;
        }

        public void setQ13Comments( String q13Comments )
        {
            this.q13Comments = q13Comments ;
        }


        public String getQ14Checkbox()
        {
            return q14Checkbox ;
        }

        public void setQ14Checkbox( String q14Checkbox )
        {
            this.q14Checkbox = q14Checkbox ;
        }


        public String getQ14Comments()
        {
            return q14Comments ;
        }

        public void setQ14Comments( String q14Comments )
        {
            this.q14Comments = q14Comments ;
        }


        public String getQ15Checkbox()
        {
            return q15Checkbox ;
        }

        public void setQ15Checkbox( String q15Checkbox )
        {
            this.q15Checkbox = q15Checkbox ;
        }


        public String getQ15Comments()
        {
            return q15Comments ;
        }

        public void setQ15Comments( String q15Comments )
        {
            this.q15Comments = q15Comments ;
        }


        public String getQ16Checkbox()
        {
            return q16Checkbox ;
        }

        public void setQ16Checkbox( String q16Checkbox )
        {
            this.q16Checkbox = q16Checkbox ;
        }


        public String getQ16Comments()
        {
            return q16Comments ;
        }

        public void setQ16Comments( String q16Comments )
        {
            this.q16Comments = q16Comments ;
        }


        public String getQ17Checkbox()
        {
            return q17Checkbox ;
        }

        public void setQ17Checkbox( String q17Checkbox )
        {
            this.q17Checkbox = q17Checkbox ;
        }


        public String getQ17Comments()
        {
            return q17Comments ;
        }

        public void setQ17Comments( String q17Comments )
        {
            this.q17Comments = q17Comments ;
        }



        
        private boolean dataLoadedFromDatabase()
        {
            return dataLoadedFromDatabase ;
        }

        private Map buildDataMap()
        {
            Map data = new HashMap();
            data.put( idColumnName , String.valueOf(  this.id ) );
            data.put( spaceIDColumnName , String.valueOf(  this.spaceID ) );
            data.put( q1DimsHColumnName , this.q1DimsH );
            data.put( q1DimsWColumnName , this.q1DimsW );
            data.put( q1DimsLColumnName , this.q1DimsL );
            data.put( q1CommentsColumnName , this.q1Comments );
            data.put( q2CheckboxColumnName , this.q2Checkbox );
            data.put( q2DescColumnName , this.q2Desc );
            data.put( q3CheckboxColumnName , this.q3Checkbox );
            data.put( q3CommentsColumnName , this.q3Comments );
            data.put( q4CheckboxColumnName , this.q4Checkbox );
            data.put( q4DimsHColumnName , this.q4DimsH );
            data.put( q4DimsWColumnName , this.q4DimsW );
            data.put( q4CommentsColumnName , this.q4Comments );
            data.put( q5CheckboxColumnName , this.q5Checkbox );
            data.put( q5CommentsColumnName , this.q5Comments );
            data.put( q6CheckboxColumnName , this.q6Checkbox );
            data.put( q6CommentsColumnName , this.q6Comments );
            data.put( q7CheckboxColumnName , this.q7Checkbox );
            data.put( q7RatingColumnName , this.q7RatingNull ? null : String.valueOf( this.q7Rating ) );
            data.put( q7CommentsColumnName , this.q7Comments );
            data.put( q8CheckboxColumnName , this.q8Checkbox );
            data.put( q8RatingColumnName , this.q8RatingNull ? null : String.valueOf( this.q8Rating ) );
            data.put( q8CommentsColumnName , this.q8Comments );
            data.put( q9CheckboxColumnName , this.q9Checkbox );
            data.put( q9RatingColumnName , this.q9RatingNull ? null : String.valueOf( this.q9Rating ) );
            data.put( q9CommentsColumnName , this.q9Comments );
            data.put( q10CheckboxColumnName , this.q10Checkbox );
            data.put( q10RatingColumnName , this.q10RatingNull ? null : String.valueOf( this.q10Rating ) );
            data.put( q10CommentsColumnName , this.q10Comments );
            data.put( q11CheckboxColumnName , this.q11Checkbox );
            data.put( q11CommentsColumnName , this.q11Comments );
            data.put( q12CheckboxColumnName , this.q12Checkbox );
            data.put( q12CommentsColumnName , this.q12Comments );
            data.put( q13CheckboxColumnName , this.q13Checkbox );
            data.put( q13CommentsColumnName , this.q13Comments );
            data.put( q14CheckboxColumnName , this.q14Checkbox );
            data.put( q14CommentsColumnName , this.q14Comments );
            data.put( q15CheckboxColumnName , this.q15Checkbox );
            data.put( q15CommentsColumnName , this.q15Comments );
            data.put( q16CheckboxColumnName , this.q16Checkbox );
            data.put( q16CommentsColumnName , this.q16Comments );
            data.put( q17CheckboxColumnName , this.q17Checkbox );
            data.put( q17CommentsColumnName , this.q17Comments );
            return data ;
        }

        /** update a row object based on a search */
        public void update( Connection con , String column , String searchText ) throws SQLException
        {
            imp.update( con , column , searchText , buildDataMap() );
        }

        /** update a row object based on a search */
        public void update( String column , String searchText ) throws SQLException
        {
            imp.update( column , searchText , buildDataMap() );
        }

        /** update a row object based on the id */
        public void update( Connection con ) throws SQLException
        {
            imp.update( con , id , buildDataMap() );
        }

        /** update a row object based on the id */
        public void update() throws SQLException
        {
            imp.update( id , buildDataMap() );
        }

        /** create a new row complete with a new ID.

            The current ID is ignored.  The new ID is placed in the row.

            @return the new row ID 
        */
        public long insert( Connection con ) throws SQLException
        {
            return imp.insertAndGetID( con , buildDataMap() );
        }

        /** create a new row complete with a new ID.

            The current ID is ignored.  The new ID is placed in the row.

            @return the new row ID 
        */
        public long insert() throws SQLException
        {
            return imp.insertAndGetID( buildDataMap() );
        }

        /** delete a row object based on the id */
        public void delete( Connection con ) throws SQLException
        {
            imp.delete( con , id );
        }

        /** delete a row object based on the id */
        public void delete() throws SQLException
        {
            imp.delete( id );
        }


    }

    /** Return an empty row object */
    public static Row getRow()
    {
        return imp.getRow();
    }

    /** Instantiate a Row object and fill its content based on a search for the ID. 
     *
     * Return null if not found.
     */
    public static Row getRow( Connection con , int id ) throws SQLException
    {
        return imp.getRow( con , id );
    }

    /** Instantiate a Row object and fill its content based on a search for the ID. 
     *
     * Return null if not found.
     */
    public static Row getRow( long id ) throws SQLException
    {
        return imp.getRow( id );
    }

    /** Instantiate a Row object and fill its content based on a search
     *
     * Return null if not found.
     */
    public static Row getRow( Connection con , String column , String searchText ) throws SQLException
    {
        return imp.getRow( con , column , searchText );
    }

    /** Instantiate a Row object and fill its content based on a search
     *
     * Return null if not found.
     */
    public static Row getRow( String column , String searchText ) throws SQLException
    {
        return imp.getRow( column , searchText );
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows( Connection con , String column , String searchText ) throws SQLException
    {
        return imp.getRows( con , column , searchText );
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows( String column , String searchText ) throws SQLException
    {
        return imp.getRows( column , searchText );
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows( Connection con , String column , String[] searchText ) throws SQLException
    {
        return imp.getRows( con , column , searchText );
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows( String column , String[] searchText ) throws SQLException
    {
        return imp.getRows( column , searchText );
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows( Connection con , String column , int searchValue ) throws SQLException
    {
        return imp.getRows( con , column , String.valueOf( searchValue ) );
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows( String column , int searchValue ) throws SQLException
    {
        return imp.getRows( column , String.valueOf( searchValue ) );
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows( Connection con , String column , int[] searchValues ) throws SQLException
    {
        return imp.getRows( con , column , Str.toStringArray( searchValues ) );
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows( String column , int[] searchValues ) throws SQLException
    {
        return imp.getRows( column , Str.toStringArray( searchValues ) );
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows( Connection con , String whereClause ) throws SQLException
    {
        return imp.getRows( con , whereClause );
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows( String whereClause ) throws SQLException
    {
        return imp.getRows( whereClause );
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getAllRows( Connection con ) throws SQLException
    {
        return imp.getAllRows( con );
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getAllRows() throws SQLException
    {
        return imp.getAllRows();
    }

    public static DBResults search( Connection con , String column , String searchText , String[] dataColumns ) throws SQLException
    {
        return imp.search( con , column , searchText , dataColumns );
    }

    public static DBResults search( String column , String searchText , String[] dataColumns ) throws SQLException
    {
        return imp.search( column , searchText , dataColumns );
    }

    public static DBResults search( Connection con , String column , String[] searchText , String[] dataColumns ) throws SQLException
    {
        return imp.search( con , column , searchText , dataColumns );
    }

    public static DBResults search( String column , String searchText[] , String[] dataColumns ) throws SQLException
    {
        return imp.search( column , searchText , dataColumns );
    }

    public static DBResults search( Connection con , String column , int searchValue , String[] dataColumns ) throws SQLException
    {
        return imp.search( con , column , searchValue , dataColumns );
    }

    public static DBResults search( String column , int searchValue , String[] dataColumns ) throws SQLException
    {
        return imp.search( column , searchValue , dataColumns );
    }

    public static DBResults search( Connection con , String column , int[] searchValues , String[] dataColumns ) throws SQLException
    {
        return imp.search( con , column , searchValues , dataColumns );
    }

    public static DBResults search( String column , int[] searchValues , String[] dataColumns ) throws SQLException
    {
        return imp.search( column , searchValues , dataColumns );
    }

    public static DBResults search( Connection con , String whereClause , String[] dataColumns ) throws SQLException
    {
        return imp.search( con , whereClause , dataColumns );
    }

    public static DBResults search( String whereClause , String[] dataColumns ) throws SQLException
    {
        return imp.search( whereClause , dataColumns );
    }

    public static DBResults search( Connection con , String[] dataColumns ) throws SQLException
    {
        return imp.search( con , dataColumns );
    }

    public static DBResults search( String[] dataColumns ) throws SQLException
    {
        return imp.search( dataColumns );
    }

    public static void update( Connection con , String column , String searchText , Map data ) throws SQLException
    {
        imp.update( con , column , searchText , data );
    }

    public static void update( String column , String searchText , Map data ) throws SQLException
    {
        imp.update( column , searchText , data );
    }

    public static void delete( Connection con , long id ) throws SQLException
    {
        imp.delete( con , id );
    }

    public static void delete( long id ) throws SQLException
    {
        imp.delete( id );
    }

    public static void delete( Connection con , String column , String searchText ) throws SQLException
    {
        imp.delete( con , column , searchText );
    }

    public static void delete( String column , String searchText ) throws SQLException
    {
        imp.delete( column , searchText );
    }

    public static long insert( Connection con , Map data ) throws SQLException
    {
        return imp.insertAndGetID( con , data );
    }

    public static long insert( Map data ) throws SQLException
    {
        return imp.insertAndGetID( data );
    }



}
